---
on:
  push:
  pull_request:
  schedule:
    - cron: "0 23 * * *" # daily

jobs:
  build:
    # TODO: use ubuntu-latest
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3

      - env:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
          PGP_SIGNING_KEY: ${{ secrets.PGP_SIGNING_KEY }}
        run: |-
          make pubkey var/venv/bin/s3cmd
          gpg --batch --import --yes -- ./var/deb/pubkey.asc
          printenv -- PGP_SIGNING_KEY | gpg --batch --import --yes

      - run: |-
          make lint

      - run: |-
          make pkg

      - run: |-
          make --debug pkg

      - env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: |-
          make push s3
