---
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |-
          make lint

      - run: |-
          make pkg

      - run: |-
          make push
