---
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - env:
          PGP_SIGNING_KEY: ${{ secrets.PGP_SIGNING_KEY }}
        run: |-
          make pubkey
          gpg --batch --import --yes -- ./var/deb/pubkey.asc
          printenv -- PGP_SIGNING_KEY | gpg --batch --import --yes

      - run: |-
          make init

      - run: |-
          make lint

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          make pkg

      - run: |-
          make push
